
train:
#  - [ './data/clean.ECB.en-fr.en.trn.tokc',          './data/clean.ECB.en-fr.fr.trn.tokc',          './data/clean.ECB.en-fr.en.trn.tokc.en2fr.gdfa' ]
#  - [ './data/clean.EMEA.en-fr.en.trn.tokc',         './data/clean.EMEA.en-fr.fr.trn.tokc',         './data/clean.EMEA.en-fr.en.trn.tokc.en2fr.gdfa' ]
#  - [ './data/clean.Europarl.en-fr.en.trn.tokc',     './data/clean.Europarl.en-fr.fr.trn.tokc',     './data/clean.Europarl.en-fr.en.trn.tokc.en2fr.gdfa' ]
#  - [ './data/clean.GNOME.en-fr.en.trn.tokc',        './data/clean.GNOME.en-fr.fr.trn.tokc',        './data/clean.GNOME.en-fr.en.trn.tokc.en2fr.gdfa' ]
#  - [ './data/clean.JRC-Acquis.en-fr.en.trn.tokc',   './data/clean.JRC-Acquis.en-fr.fr.trn.tokc',   './data/clean.JRC-Acquis.en-fr.en.trn.tokc.en2fr.gdfa' ]
#  - [ './data/clean.KDE4.en-fr.en.trn.tokc',         './data/clean.KDE4.en-fr.fr.trn.tokc',         './data/clean.KDE4.en-fr.en.trn.tokc.en2fr.gdfa' ]
  - [ './data/clean.news-commentary-v14.en.trn.tokc','./data/clean.news-commentary-v14.fr.trn.tokc','./data/clean.news-commentary-v14.en.trn.tokc.en2fr.gdfa' ]
#  - [ './data/clean.TED2013.en-fr.en.trn.tokc',      './data/clean.TED2013.en-fr.fr.trn.tokc',      './data/clean.TED2013.en-fr.en.trn.tokc.en2fr.gdfa' ]
#  - [ './data/clean.Wikipedia.en-fr.en.trn.tokc',    './data/clean.Wikipedia.en-fr.fr.trn.tokc',    './data/clean.Wikipedia.en-fr.en.trn.tokc.en2fr.gdfa' ]
valid:
#  - [ './data/clean.ECB.en-fr.en.val.tokc',          './data/clean.ECB.en-fr.fr.val.tokc',          './data/clean.ECB.en-fr.en.val.tokc.en2fr.gdfa' ]
#  - [ './data/clean.EMEA.en-fr.en.val.tokc',         './data/clean.EMEA.en-fr.fr.val.tokc',         './data/clean.EMEA.en-fr.en.val.tokc.en2fr.gdfa' ]
#  - [ './data/clean.Europarl.en-fr.en.val.tokc',     './data/clean.Europarl.en-fr.fr.val.tokc',     './data/clean.Europarl.en-fr.en.val.tokc.en2fr.gdfa' ]
#  - [ './data/clean.GNOME.en-fr.en.val.tokc',        './data/clean.GNOME.en-fr.fr.val.tokc',        './data/clean.GNOME.en-fr.en.val.tokc.en2fr.gdfa' ]
#  - [ './data/clean.JRC-Acquis.en-fr.en.val.tokc',   './data/clean.JRC-Acquis.en-fr.fr.val.tokc',   './data/clean.JRC-Acquis.en-fr.en.val.tokc.en2fr.gdfa' ]
#  - [ './data/clean.KDE4.en-fr.en.val.tokc',         './data/clean.KDE4.en-fr.fr.val.tokc',         './data/clean.KDE4.en-fr.en.val.tokc.en2fr.gdfa' ]
  - [ './data/clean.news-commentary-v14.en.val.tokc','./data/clean.news-commentary-v14.fr.val.tokc','./data/clean.news-commentary-v14.en.val.tokc.en2fr.gdfa' ]
#  - [ './data/clean.TED2013.en-fr.en.val.tokc',      './data/clean.TED2013.en-fr.fr.val.tokc',      './data/clean.TED2013.en-fr.en.val.tokc.en2fr.gdfa' ]
#  - [ './data/clean.Wikipedia.en-fr.en.val.tokc',    './data/clean.Wikipedia.en-fr.fr.val.tokc',    './data/clean.Wikipedia.en-fr.en.val.tokc.en2fr.gdfa' ]
max_length: 90
swap_bitext: 0.5
batch_size: [32, 32]
steps: 
  mlm:  { w: 1.0, p_single: 0.15, p_mask: 0.15, r_same: 0.1, r_rand: 0.1 }
  ali:  { w: 1.0, R: 1.0, align_scale: 0.001 }
checkpoint_every_steps: 5000
validation_every_steps: 5000
report_every_steps: 100

